// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".
import * as path from 'path';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import { Construct } from 'constructs';

/**
 * Props for VpcResourceTaggingFunction
 */
export interface VpcResourceTaggingFunctionProps extends lambda.FunctionOptions {
}

/**
 * An AWS Lambda function which executes src/vpc/vpc-resource-tagging.
 */
export class VpcResourceTaggingFunction extends lambda.Function {
  constructor(scope: Construct, id: string, props?: VpcResourceTaggingFunctionProps) {
    super(scope, id, {
      description: 'src/vpc/vpc-resource-tagging.lambda.ts',
      ...props,
      runtime: new lambda.Runtime('nodejs18.x', lambda.RuntimeFamily.NODEJS),
      handler: 'index.handler',
      code: lambda.Code.fromAsset(path.join(__dirname, '../../assets/vpc/vpc-resource-tagging.lambda')),
    });
    this.addEnvironment('AWS_NODEJS_CONNECTION_REUSE_ENABLED', '1', { removeInEdge: true });
  }
}